spring.datasource.url=jdbc:mysql://localhost:3306/dbcards?createDatabaseIfNotExist=true
spring.datasource.username=dbc_user
spring.datasource.password=Dbc@12345


# Allow external access (phone / Expo)
server.address=0.0.0.0
server.port=8083


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patilsainath562@gmail.com
spring.mail.password=aopp ohnj ceyp gqrf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sms.api-id=APIuhiNX2Qr143139
sms.api-password=WNqi3puo
sms.sender=VENTBD
sms.template-id=189309
sms.base-url=http://bulksmsplans.com/api/send_sms

# OTP mode switch
otp.sms.enabled=false

##Mongodb connection
#spring.data.mongodb.uri=mongodb://localhost:27017/dbcardsfiles
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=20MB

# ===============================
# DATABASE
# ===============================
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=false
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
## ===============================
## MAIL CONFIG
## ===============================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## ===============================
## MONGODB
## ===============================
#spring.data.mongodb.uri=${MONGO_URI}
#
#
#
